# Import des templates de jobs pré-configurés
include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

services:
  - postgres:14
  - redis:latest


variables:
  POSTGRES_DB: decidim_test
  POSTGRES_USER: decidim
  POSTGRES_PASSWORD: "TEST-ohm5phaisohHie2ohh7aeweecahdoy5p"

stages:
  - test
  - analyze
  - version
  - build

coverage-024:
  image: ruby:2.7.1
  stage: test
  only:
    - merge_requests
    - main
    - tags
  cache:
    key: gems
    paths:
      - vendor/ruby
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  variables:
    DATABASE_HOST: "postgres"
    # trunk-ignore(gitleaks/generic-api-key)
    DATABASE_PASSWORD: "TEST-ohm5phaisohHie2ohh7aeweecahdoy5p"
    DATABASE_USERNAME: "decidim"
    DISABLED_DOCKER_COMPOSE: "true"
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
    - gem install bundler -v 2.3.6
    - bundle config set path 'vendor'
    - RAILS_ENV=development bundle install -j $(nproc)
    - bundle exec rake test_app
  script:
    - RAILS_ENV=test bundle exec rspec spec --format progress --format RspecJunitFormatter --exclude-pattern ./**/vendor/**/*_spec.rb --out rspec.xml
