services:
  pg:
    image: postgres:12
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=TEST-baeGhi4Ohtahcee5eejoaxaiwaezaiGo
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_test
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass my_insecure_password
    volumes:
      - redis-data:/var/lib/redis
      - redis-conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379

  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080:1080"
      - "3587:1025"

volumes:
  pg-data: {}
  redis-data:
  redis-conf:
