# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decidim.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("decidim.proto", :syntax => :proto3) do
    add_message "voca_decidim.GetSettingsResponse" do
      optional :id, :uint64, 1
      proto3_optional :permission_settings, :message, 2, "voca_decidim.DecidimOrganizationPermissionSettings"
      proto3_optional :naming_settings, :message, 3, "voca_decidim.DecidimOrganizationNamingSettings"
      proto3_optional :locale_settings, :message, 4, "voca_decidim.DecidimOrganizationLocaleSettings"
      proto3_optional :smtp_settings, :message, 5, "voca_decidim.DecidimOrganizationSMTPSettings"
      proto3_optional :color_settings, :message, 6, "voca_decidim.DecidimOrganizationColorSettings"
      proto3_optional :file_upload_settings, :message, 7, "voca_decidim.DecidimOrganizationFileUploadSettings"
      proto3_optional :feature_settings, :message, 8, "voca_decidim.DecidimOrganizationFeatureFlagSettings"
      optional :created_at, :message, 9, "google.protobuf.Timestamp"
    end
    add_message "voca_decidim.SetSettingsRequest" do
      proto3_optional :permission_settings, :message, 1, "voca_decidim.DecidimOrganizationPermissionSettings"
      proto3_optional :naming_settings, :message, 2, "voca_decidim.DecidimOrganizationNamingSettings"
      proto3_optional :locale_settings, :message, 3, "voca_decidim.DecidimOrganizationLocaleSettings"
      proto3_optional :smtp_settings, :message, 4, "voca_decidim.DecidimOrganizationSMTPSettings"
      proto3_optional :color_settings, :message, 5, "voca_decidim.DecidimOrganizationColorSettings"
      proto3_optional :file_upload_settings, :message, 6, "voca_decidim.DecidimOrganizationFileUploadSettings"
      proto3_optional :feature_settings, :message, 7, "voca_decidim.DecidimOrganizationFeatureFlagSettings"
    end
    add_message "voca_decidim.DecidimOrganizationPermissionSettings" do
      proto3_optional :force_users_to_authenticate_before_access_organization, :bool, 1
      optional :users_registration_mode, :enum, 2, "voca_decidim.SETTINGS_REGISTER_MODE_OPTION"
    end
    add_message "voca_decidim.DecidimOrganizationNamingSettings" do
      optional :host, :string, 1
      repeated :secondary_hosts, :string, 2
      optional :name, :string, 3
      optional :reference_prefix, :string, 4
    end
    add_message "voca_decidim.DecidimOrganizationLocaleSettings" do
      optional :default_locale, :string, 1
      repeated :available_locales, :string, 2
    end
    add_message "voca_decidim.DecidimOrganizationSMTPSettings" do
      optional :from_label, :string, 1
      optional :from_email, :string, 2
      optional :address, :string, 3
      optional :port, :string, 4
      optional :authentication, :enum, 5, "voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION"
      optional :username, :string, 6
      optional :password, :string, 7
      optional :domain, :string, 8
      optional :enable_starttls_auto, :bool, 9
      optional :openssl_verify_mode, :enum, 10, "voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION"
    end
    add_message "voca_decidim.DecidimOrganizationColorSettings" do
      optional :alert, :string, 1
      optional :primary, :string, 2
      optional :success, :string, 3
      optional :warning, :string, 4
      optional :highlight, :string, 5
      optional :secondary, :string, 6
      optional :highlight_alternative, :string, 7
    end
    add_message "voca_decidim.DecidimOrganizationFileUploadSettings" do
      optional :maximum_file_size_avatar, :float, 1
      optional :maximum_file_size_default, :float, 2
      repeated :allowed_content_types_admin, :string, 3
      repeated :allowed_content_types_default, :string, 4
      repeated :allowed_file_extensions_admin, :string, 5
      repeated :allowed_file_extensions_default, :string, 6
    end
    add_message "voca_decidim.DecidimOrganizationFeatureFlagSettings" do
      repeated :available_authorizations, :string, 1
      optional :badges_enabled, :bool, 2
      optional :user_groups_enabled, :bool, 3
      optional :enable_machine_translations, :bool, 4
      optional :machine_translation_display_priority, :enum, 5, "voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION"
    end
    add_message "voca_decidim.SeedRequest" do
      optional :admin_email, :string, 1
      optional :host, :string, 2
      optional :name, :string, 3
      optional :short_name, :string, 4
      optional :default_locale, :string, 5
      optional :available_locales, :string, 6
      optional :system_email, :string, 7
      optional :system_password, :string, 8
    end
    add_message "voca_decidim.BackupCredentialsReq" do
      optional :cypherKey, :string, 1
      optional :cypherIV, :string, 2
    end
    add_enum "voca_decidim.SETTINGS_REGISTER_MODE_OPTION" do
      value :SETTINGS_REGISTER_MODE_REGISTER_AND_LOGIN, 0
      value :SETTINGS_REGISTER_MODE_LOGIN, 1
      value :SETTINGS_REGISTER_MODE_EXTERNAL, 2
    end
    add_enum "voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION" do
      value :SETTINGS_SMTP_AUTHENTICATION_PLAIN, 0
      value :SETTINGS_SMTP_AUTHENTICATION_LOGIN, 1
      value :SETTINGS_SMTP_AUTHENTICATION_CRAM_MD5, 2
      value :SETTINGS_SMTP_AUTHENTICATION_NONE, 3
    end
    add_enum "voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION" do
      value :SETTINGS_SMTP_OPENSSL_NONE, 0
      value :SETTINGS_SMTP_OPENSSL_PEER, 1
    end
    add_enum "voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION" do
      value :SETTINGS_MACHINE_TRANSLATION_PRIORITY_ORIGINAL, 0
      value :SETTINGS_MACHINE_TRANSLATION_PRIORITY_TRANSLATED, 1
    end
  end
end

module VocaDecidim
  GetSettingsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.GetSettingsResponse").msgclass
  SetSettingsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SetSettingsRequest").msgclass
  DecidimOrganizationPermissionSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationPermissionSettings").msgclass
  DecidimOrganizationNamingSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationNamingSettings").msgclass
  DecidimOrganizationLocaleSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationLocaleSettings").msgclass
  DecidimOrganizationSMTPSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationSMTPSettings").msgclass
  DecidimOrganizationColorSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationColorSettings").msgclass
  DecidimOrganizationFileUploadSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationFileUploadSettings").msgclass
  DecidimOrganizationFeatureFlagSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.DecidimOrganizationFeatureFlagSettings").msgclass
  SeedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SeedRequest").msgclass
  BackupCredentialsReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.BackupCredentialsReq").msgclass
  SETTINGS_REGISTER_MODE_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SETTINGS_REGISTER_MODE_OPTION").enummodule
  SETTINGS_SMTP_AUTHENTICATION_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION").enummodule
  SETTINGS_SMTP_OPENSSL_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION").enummodule
  SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION").enummodule
end
