# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: decidim.proto for package 'voca_decidim'

require 'grpc'
require_relative 'decidim_pb'

module VocaDecidim
  module Decidim
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'voca_decidim.Decidim'

      rpc :GetSettings, ::Google::Protobuf::Empty, ::VocaDecidim::GetSettingsResponse
      rpc :SetSettings, ::VocaDecidim::SetSettingsRequest, ::Google::Protobuf::Empty
      rpc :Seed, ::VocaDecidim::SeedRequest, ::Google::Protobuf::Empty
      rpc :CompileAssets, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
      rpc :Backup, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
      rpc :ConfigBackup, ::VocaDecidim::BackupCredentialsReq, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
